#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnetfilter_conntrack
Version  : 1.0.6
Release  : 9
URL      : http://ftp.netfilter.org/pub/libnetfilter_conntrack/libnetfilter_conntrack-1.0.6.tar.bz2
Source0  : http://ftp.netfilter.org/pub/libnetfilter_conntrack/libnetfilter_conntrack-1.0.6.tar.bz2
Summary  : netfilter userspace conntrack access library
Group    : Development/Tools
License  : GPL-2.0
Requires: libnetfilter_conntrack-lib
BuildRequires : pkgconfig(libmnl)
BuildRequires : pkgconfig(libnfnetlink)

%description
libnetfilter_conntrack - userspace library for the connection tracking system
(C) 2005-2011 Pablo Neira Ayuso <pablo@netfilter.org>
=============================================================================

%package dev
Summary: dev components for the libnetfilter_conntrack package.
Group: Development
Requires: libnetfilter_conntrack-lib
Provides: libnetfilter_conntrack-devel

%description dev
dev components for the libnetfilter_conntrack package.


%package lib
Summary: lib components for the libnetfilter_conntrack package.
Group: Libraries

%description lib
lib components for the libnetfilter_conntrack package.


%prep
%setup -q -n libnetfilter_conntrack-1.0.6

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnetfilter_conntrack/libnetfilter_conntrack.h
/usr/include/libnetfilter_conntrack/libnetfilter_conntrack_dccp.h
/usr/include/libnetfilter_conntrack/libnetfilter_conntrack_icmp.h
/usr/include/libnetfilter_conntrack/libnetfilter_conntrack_ipv4.h
/usr/include/libnetfilter_conntrack/libnetfilter_conntrack_ipv6.h
/usr/include/libnetfilter_conntrack/libnetfilter_conntrack_sctp.h
/usr/include/libnetfilter_conntrack/libnetfilter_conntrack_tcp.h
/usr/include/libnetfilter_conntrack/libnetfilter_conntrack_udp.h
/usr/include/libnetfilter_conntrack/linux_nfnetlink_conntrack.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
